### ISSUE TITLE
Block::render() should remove namespaces from the default view

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [RadoslavGeorgiev/rila-framework#2]
If a block is within a namespace, ex. `Theme\Block\Text`, the plugin is looking for `views/blocks/theme/block/text' instead of`views/blocks/text`.

**Comment by iantsch** [comment]
See #3

**Comment by RadoslavGeorgiev** [comment]
Fixed in 4ce8795dee2820521c120c33bcd256a4bc8c5aec
